export const DATE_FORMAT = 'yyyy-MM-dd'
export const SHORT_DATE_FORMAT = 'MM-dd'
export const TIME_FORMAT = 'HH:mm'
export const DATETIME_FORMAT = 'yyyy-MM-dd HH:mm'
export const LONG_DATE_FORMAT = 'MMM d, YYY'
export const LONG_DATETIME_FORMAT = 'MMM d, YYY HH:mm'
